"""initial schema

Revision ID: ced7b041d8c4
Revises: 
Create Date: 2026-06-06 06:42:45.962728

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ced7b041d8c4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('panel_url', sa.String(length=512), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'WAITING_ADMIN', 'CONFIRMED', 'REJECTED', 'APPLIED', 'FAILED', name='paymentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('payment_code', sa.String(length=32), nullable=False),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_requests_payment_code'), ['payment_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_requests_user_id'), ['user_id'], unique=False)

    op.create_table('vpn_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('external_client_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_url_direct', sa.Text(), nullable=True),
    sa.Column('subscription_url_ru_proxy', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vpn_clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vpn_clients_user_id'), ['user_id'], unique=False)

    op.create_table('client_server_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vpn_client_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('inbound_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.Enum('VMESS', 'VLESS', 'TROJAN', name='protocol', native_enum=False, length=16), nullable=False),
    sa.Column('client_uuid', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('sub_id', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vpn_client_id'], ['vpn_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_server_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_server_mappings_server_id'), ['server_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_server_mappings_vpn_client_id'), ['vpn_client_id'], unique=False)

    op.create_table('payment_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_request_id', sa.Integer(), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=512), nullable=True),
    sa.Column('file_type', sa.Enum('TEXT', 'PHOTO', 'DOCUMENT', name='attachmenttype', native_enum=False, length=16), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_request_id'], ['payment_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_attachments_payment_request_id'), ['payment_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_attachments_payment_request_id'))

    op.drop_table('payment_attachments')
    with op.batch_alter_table('client_server_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_server_mappings_vpn_client_id'))
        batch_op.drop_index(batch_op.f('ix_client_server_mappings_server_id'))

    op.drop_table('client_server_mappings')
    with op.batch_alter_table('vpn_clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vpn_clients_user_id'))

    op.drop_table('vpn_clients')
    with op.batch_alter_table('payment_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_requests_status'))
        batch_op.drop_index(batch_op.f('ix_payment_requests_payment_code'))

    op.drop_table('payment_requests')
    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    op.drop_table('servers')
    # ### end Alembic commands ###
